# Generated by Django 2.2.27 on 2022-05-02 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuanzi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='following',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to=settings.AUTH_USER_MODEL)),
                ('fan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
