# Generated by Django 2.2.27 on 2022-05-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuanzi', '0002_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
