# Generated by Django 3.2.13 on 2022-05-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuanzi', '0009_alter_userinfo_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='未命名', max_length=50, verbose_name='文章标题'),
        ),
    ]
