# Generated by Django 2.2.27 on 2022-05-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuanzi', '0013_auto_20220519_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='telephone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
