# Generated by Django 2.2.27 on 2022-05-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuanzi', '0004_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Applications',
        ),
    ]
