# Generated by Django 3.2.13 on 2022-05-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuanzi', '0008_alter_userinfo_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='telephone',
            field=models.CharField(default=5201314, max_length=11),
        ),
    ]
